// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Playground.Infrastructure.Data;

#nullable disable

namespace Playground.Infrastructure.Migrations
{
    [DbContext(typeof(PetDbContext))]
    [Migration("20260711154351_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Playground.Domain.Entities.Pet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PetType")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SuggestedDonation")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasDiscriminator<string>("PetType").HasValue("Pet");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Playground.Domain.Entities.Cat", b =>
                {
                    b.HasBaseType("Playground.Domain.Entities.Pet");

                    b.HasDiscriminator().HasValue("Cat");
                });

            modelBuilder.Entity("Playground.Domain.Entities.Dog", b =>
                {
                    b.HasBaseType("Playground.Domain.Entities.Pet");

                    b.HasDiscriminator().HasValue("Dog");
                });
#pragma warning restore 612, 618
        }
    }
}
